backend:
  replicas: 1
  image:
    repository: ghcr.io/i-am-wizard/word-manager-backend
    tag: 1.0.0-15
  env:
    datasourceUrl: jdbc:postgresql://postgres:5432/hello_db
    datasourceUser: user
    datasourcePassword: password
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi  

postgres:
  replicas: 1
  image: 
    repository: postgres
    tag: latest
  pullPolicy: Always
  env:
    db: hello_db
    user: user
    password: password
  storageClassName: local-path
  storageSize: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

frontend:
  replicas: 1
  image: 
    repository: ghcr.io/i-am-wizard/word-manager-frontend
    tag: 1.0.0-5
  serviceType: NodePort
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi