apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "Waiting for Postgres..."
                sleep 2
              done
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.env.datasourceUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.backend.env.datasourceUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.backend.env.datasourcePassword }}
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx128m"  
          {{- with .Values.backend.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}    
