apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
    - port: 80
      targetPort: 80
      {{- if eq .Values.frontend.serviceType "NodePort" }}
      nodePort: 30080
      {{- end }}
  selector:
    app: frontend
